// Code generated by MockGen. DO NOT EDIT.
// Source: cityaqrpc/cityaq.wasm.pb.go

// Package mock_cityaqrpc is a generated GoMock package.
package mock_cityaqrpc

import (
	cityaqrpc "github.com/ctessum/cityaq/cityaqrpc"
	gomock "github.com/golang/mock/gomock"
	grpc_wasm "github.com/johanbrandhorst/grpc-wasm"
	context "golang.org/x/net/context"
	reflect "reflect"
)

// MockCityAQClient is a mock of CityAQClient interface
type MockCityAQClient struct {
	ctrl     *gomock.Controller
	recorder *MockCityAQClientMockRecorder
}

// MockCityAQClientMockRecorder is the mock recorder for MockCityAQClient
type MockCityAQClientMockRecorder struct {
	mock *MockCityAQClient
}

// NewMockCityAQClient creates a new mock instance
func NewMockCityAQClient(ctrl *gomock.Controller) *MockCityAQClient {
	mock := &MockCityAQClient{ctrl: ctrl}
	mock.recorder = &MockCityAQClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCityAQClient) EXPECT() *MockCityAQClientMockRecorder {
	return m.recorder
}

// Cities mocks base method
func (m *MockCityAQClient) Cities(ctx context.Context, in *cityaqrpc.CitiesRequest, opts ...grpc_wasm.CallOption) (*cityaqrpc.CitiesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Cities", varargs...)
	ret0, _ := ret[0].(*cityaqrpc.CitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cities indicates an expected call of Cities
func (mr *MockCityAQClientMockRecorder) Cities(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cities", reflect.TypeOf((*MockCityAQClient)(nil).Cities), varargs...)
}

// CityGeometry mocks base method
func (m *MockCityAQClient) CityGeometry(ctx context.Context, in *cityaqrpc.CityGeometryRequest, opts ...grpc_wasm.CallOption) (*cityaqrpc.CityGeometryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CityGeometry", varargs...)
	ret0, _ := ret[0].(*cityaqrpc.CityGeometryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CityGeometry indicates an expected call of CityGeometry
func (mr *MockCityAQClientMockRecorder) CityGeometry(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CityGeometry", reflect.TypeOf((*MockCityAQClient)(nil).CityGeometry), varargs...)
}

// EmissionsGrid mocks base method
func (m *MockCityAQClient) EmissionsGrid(ctx context.Context, in *cityaqrpc.EmissionsGridRequest, opts ...grpc_wasm.CallOption) (*cityaqrpc.EmissionsGridResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EmissionsGrid", varargs...)
	ret0, _ := ret[0].(*cityaqrpc.EmissionsGridResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmissionsGrid indicates an expected call of EmissionsGrid
func (mr *MockCityAQClientMockRecorder) EmissionsGrid(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmissionsGrid", reflect.TypeOf((*MockCityAQClient)(nil).EmissionsGrid), varargs...)
}

// EmissionsMap mocks base method
func (m *MockCityAQClient) EmissionsMap(ctx context.Context, in *cityaqrpc.EmissionsMapRequest, opts ...grpc_wasm.CallOption) (*cityaqrpc.EmissionsMapResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EmissionsMap", varargs...)
	ret0, _ := ret[0].(*cityaqrpc.EmissionsMapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmissionsMap indicates an expected call of EmissionsMap
func (mr *MockCityAQClientMockRecorder) EmissionsMap(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmissionsMap", reflect.TypeOf((*MockCityAQClient)(nil).EmissionsMap), varargs...)
}

// EmissionsGridBounds mocks base method
func (m *MockCityAQClient) EmissionsGridBounds(ctx context.Context, in *cityaqrpc.EmissionsGridBoundsRequest, opts ...grpc_wasm.CallOption) (*cityaqrpc.EmissionsGridBoundsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EmissionsGridBounds", varargs...)
	ret0, _ := ret[0].(*cityaqrpc.EmissionsGridBoundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmissionsGridBounds indicates an expected call of EmissionsGridBounds
func (mr *MockCityAQClientMockRecorder) EmissionsGridBounds(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmissionsGridBounds", reflect.TypeOf((*MockCityAQClient)(nil).EmissionsGridBounds), varargs...)
}

// MapScale mocks base method
func (m *MockCityAQClient) MapScale(ctx context.Context, in *cityaqrpc.MapScaleRequest, opts ...grpc_wasm.CallOption) (*cityaqrpc.MapScaleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MapScale", varargs...)
	ret0, _ := ret[0].(*cityaqrpc.MapScaleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapScale indicates an expected call of MapScale
func (mr *MockCityAQClientMockRecorder) MapScale(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapScale", reflect.TypeOf((*MockCityAQClient)(nil).MapScale), varargs...)
}

// MockCityAQServer is a mock of CityAQServer interface
type MockCityAQServer struct {
	ctrl     *gomock.Controller
	recorder *MockCityAQServerMockRecorder
}

// MockCityAQServerMockRecorder is the mock recorder for MockCityAQServer
type MockCityAQServerMockRecorder struct {
	mock *MockCityAQServer
}

// NewMockCityAQServer creates a new mock instance
func NewMockCityAQServer(ctrl *gomock.Controller) *MockCityAQServer {
	mock := &MockCityAQServer{ctrl: ctrl}
	mock.recorder = &MockCityAQServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCityAQServer) EXPECT() *MockCityAQServerMockRecorder {
	return m.recorder
}

// Cities mocks base method
func (m *MockCityAQServer) Cities(arg0 context.Context, arg1 *cityaqrpc.CitiesRequest) (*cityaqrpc.CitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cities", arg0, arg1)
	ret0, _ := ret[0].(*cityaqrpc.CitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cities indicates an expected call of Cities
func (mr *MockCityAQServerMockRecorder) Cities(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cities", reflect.TypeOf((*MockCityAQServer)(nil).Cities), arg0, arg1)
}

// CityGeometry mocks base method
func (m *MockCityAQServer) CityGeometry(arg0 context.Context, arg1 *cityaqrpc.CityGeometryRequest) (*cityaqrpc.CityGeometryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CityGeometry", arg0, arg1)
	ret0, _ := ret[0].(*cityaqrpc.CityGeometryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CityGeometry indicates an expected call of CityGeometry
func (mr *MockCityAQServerMockRecorder) CityGeometry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CityGeometry", reflect.TypeOf((*MockCityAQServer)(nil).CityGeometry), arg0, arg1)
}

// EmissionsGrid mocks base method
func (m *MockCityAQServer) EmissionsGrid(arg0 context.Context, arg1 *cityaqrpc.EmissionsGridRequest) (*cityaqrpc.EmissionsGridResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmissionsGrid", arg0, arg1)
	ret0, _ := ret[0].(*cityaqrpc.EmissionsGridResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmissionsGrid indicates an expected call of EmissionsGrid
func (mr *MockCityAQServerMockRecorder) EmissionsGrid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmissionsGrid", reflect.TypeOf((*MockCityAQServer)(nil).EmissionsGrid), arg0, arg1)
}

// EmissionsMap mocks base method
func (m *MockCityAQServer) EmissionsMap(arg0 context.Context, arg1 *cityaqrpc.EmissionsMapRequest) (*cityaqrpc.EmissionsMapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmissionsMap", arg0, arg1)
	ret0, _ := ret[0].(*cityaqrpc.EmissionsMapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmissionsMap indicates an expected call of EmissionsMap
func (mr *MockCityAQServerMockRecorder) EmissionsMap(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmissionsMap", reflect.TypeOf((*MockCityAQServer)(nil).EmissionsMap), arg0, arg1)
}

// EmissionsGridBounds mocks base method
func (m *MockCityAQServer) EmissionsGridBounds(arg0 context.Context, arg1 *cityaqrpc.EmissionsGridBoundsRequest) (*cityaqrpc.EmissionsGridBoundsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmissionsGridBounds", arg0, arg1)
	ret0, _ := ret[0].(*cityaqrpc.EmissionsGridBoundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmissionsGridBounds indicates an expected call of EmissionsGridBounds
func (mr *MockCityAQServerMockRecorder) EmissionsGridBounds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmissionsGridBounds", reflect.TypeOf((*MockCityAQServer)(nil).EmissionsGridBounds), arg0, arg1)
}

// MapScale mocks base method
func (m *MockCityAQServer) MapScale(arg0 context.Context, arg1 *cityaqrpc.MapScaleRequest) (*cityaqrpc.MapScaleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapScale", arg0, arg1)
	ret0, _ := ret[0].(*cityaqrpc.MapScaleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapScale indicates an expected call of MapScale
func (mr *MockCityAQServerMockRecorder) MapScale(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapScale", reflect.TypeOf((*MockCityAQServer)(nil).MapScale), arg0, arg1)
}
