// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cityaq.proto

//+build js

package cityaqrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "github.com/johanbrandhorst/grpc-wasm"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Emission int32

const (
	Emission_UNKNOWN_EMISSION Emission = 0
	Emission_PM2_5            Emission = 1
	Emission_NH3              Emission = 2
	Emission_NOx              Emission = 3
	Emission_SOx              Emission = 4
	Emission_VOC              Emission = 5
)

var Emission_name = map[int32]string{
	0: "UNKNOWN_EMISSION",
	1: "PM2_5",
	2: "NH3",
	3: "NOx",
	4: "SOx",
	5: "VOC",
}
var Emission_value = map[string]int32{
	"UNKNOWN_EMISSION": 0,
	"PM2_5":            1,
	"NH3":              2,
	"NOx":              3,
	"SOx":              4,
	"VOC":              5,
}

func (x Emission) String() string {
	return proto.EnumName(Emission_name, int32(x))
}
func (Emission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{0}
}

type ImpactType int32

const (
	ImpactType_UNKNOWN_IMPACTTYPE ImpactType = 0
	ImpactType_Emissions          ImpactType = 1
)

var ImpactType_name = map[int32]string{
	0: "UNKNOWN_IMPACTTYPE",
	1: "Emissions",
}
var ImpactType_value = map[string]int32{
	"UNKNOWN_IMPACTTYPE": 0,
	"Emissions":          1,
}

func (x ImpactType) String() string {
	return proto.EnumName(ImpactType_name, int32(x))
}
func (ImpactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{1}
}

type CitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CitiesRequest) Reset()         { *m = CitiesRequest{} }
func (m *CitiesRequest) String() string { return proto.CompactTextString(m) }
func (*CitiesRequest) ProtoMessage()    {}
func (*CitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{0}
}
func (m *CitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitiesRequest.Unmarshal(m, b)
}
func (m *CitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitiesRequest.Marshal(b, m, deterministic)
}
func (dst *CitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitiesRequest.Merge(dst, src)
}
func (m *CitiesRequest) XXX_Size() int {
	return xxx_messageInfo_CitiesRequest.Size(m)
}
func (m *CitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CitiesRequest proto.InternalMessageInfo

type CitiesResponse struct {
	// The names of the cities
	Names                []string `protobuf:"bytes,1,rep,name=Names,proto3" json:"Names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CitiesResponse) Reset()         { *m = CitiesResponse{} }
func (m *CitiesResponse) String() string { return proto.CompactTextString(m) }
func (*CitiesResponse) ProtoMessage()    {}
func (*CitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{1}
}
func (m *CitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitiesResponse.Unmarshal(m, b)
}
func (m *CitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitiesResponse.Marshal(b, m, deterministic)
}
func (dst *CitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitiesResponse.Merge(dst, src)
}
func (m *CitiesResponse) XXX_Size() int {
	return xxx_messageInfo_CitiesResponse.Size(m)
}
func (m *CitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CitiesResponse proto.InternalMessageInfo

func (m *CitiesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type CityGeometryRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityGeometryRequest) Reset()         { *m = CityGeometryRequest{} }
func (m *CityGeometryRequest) String() string { return proto.CompactTextString(m) }
func (*CityGeometryRequest) ProtoMessage()    {}
func (*CityGeometryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{2}
}
func (m *CityGeometryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityGeometryRequest.Unmarshal(m, b)
}
func (m *CityGeometryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityGeometryRequest.Marshal(b, m, deterministic)
}
func (dst *CityGeometryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityGeometryRequest.Merge(dst, src)
}
func (m *CityGeometryRequest) XXX_Size() int {
	return xxx_messageInfo_CityGeometryRequest.Size(m)
}
func (m *CityGeometryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CityGeometryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CityGeometryRequest proto.InternalMessageInfo

func (m *CityGeometryRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

type CityGeometryResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CityGeometryResponse) Reset()         { *m = CityGeometryResponse{} }
func (m *CityGeometryResponse) String() string { return proto.CompactTextString(m) }
func (*CityGeometryResponse) ProtoMessage()    {}
func (*CityGeometryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{3}
}
func (m *CityGeometryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityGeometryResponse.Unmarshal(m, b)
}
func (m *CityGeometryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityGeometryResponse.Marshal(b, m, deterministic)
}
func (dst *CityGeometryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityGeometryResponse.Merge(dst, src)
}
func (m *CityGeometryResponse) XXX_Size() int {
	return xxx_messageInfo_CityGeometryResponse.Size(m)
}
func (m *CityGeometryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CityGeometryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CityGeometryResponse proto.InternalMessageInfo

func (m *CityGeometryResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

type Polygon struct {
	Paths                []*Path  `protobuf:"bytes,1,rep,name=Paths,proto3" json:"Paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Polygon) Reset()         { *m = Polygon{} }
func (m *Polygon) String() string { return proto.CompactTextString(m) }
func (*Polygon) ProtoMessage()    {}
func (*Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{4}
}
func (m *Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon.Unmarshal(m, b)
}
func (m *Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon.Marshal(b, m, deterministic)
}
func (dst *Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon.Merge(dst, src)
}
func (m *Polygon) XXX_Size() int {
	return xxx_messageInfo_Polygon.Size(m)
}
func (m *Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon proto.InternalMessageInfo

func (m *Polygon) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Path struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{5}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{6}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type EmissionsGridRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Dx                   float32  `protobuf:"fixed32,3,opt,name=Dx,proto3" json:"Dx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsGridRequest) Reset()         { *m = EmissionsGridRequest{} }
func (m *EmissionsGridRequest) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridRequest) ProtoMessage()    {}
func (*EmissionsGridRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{7}
}
func (m *EmissionsGridRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridRequest.Unmarshal(m, b)
}
func (m *EmissionsGridRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridRequest.Marshal(b, m, deterministic)
}
func (dst *EmissionsGridRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridRequest.Merge(dst, src)
}
func (m *EmissionsGridRequest) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridRequest.Size(m)
}
func (m *EmissionsGridRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridRequest proto.InternalMessageInfo

func (m *EmissionsGridRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *EmissionsGridRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *EmissionsGridRequest) GetDx() float32 {
	if m != nil {
		return m.Dx
	}
	return 0
}

type EmissionsGridResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EmissionsGridResponse) Reset()         { *m = EmissionsGridResponse{} }
func (m *EmissionsGridResponse) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridResponse) ProtoMessage()    {}
func (*EmissionsGridResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{8}
}
func (m *EmissionsGridResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridResponse.Unmarshal(m, b)
}
func (m *EmissionsGridResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridResponse.Marshal(b, m, deterministic)
}
func (dst *EmissionsGridResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridResponse.Merge(dst, src)
}
func (m *EmissionsGridResponse) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridResponse.Size(m)
}
func (m *EmissionsGridResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridResponse proto.InternalMessageInfo

func (m *EmissionsGridResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

type EmissionsGridBoundsRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Dx                   float32  `protobuf:"fixed32,3,opt,name=Dx,proto3" json:"Dx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsGridBoundsRequest) Reset()         { *m = EmissionsGridBoundsRequest{} }
func (m *EmissionsGridBoundsRequest) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridBoundsRequest) ProtoMessage()    {}
func (*EmissionsGridBoundsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{9}
}
func (m *EmissionsGridBoundsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridBoundsRequest.Unmarshal(m, b)
}
func (m *EmissionsGridBoundsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridBoundsRequest.Marshal(b, m, deterministic)
}
func (dst *EmissionsGridBoundsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridBoundsRequest.Merge(dst, src)
}
func (m *EmissionsGridBoundsRequest) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridBoundsRequest.Size(m)
}
func (m *EmissionsGridBoundsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridBoundsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridBoundsRequest proto.InternalMessageInfo

func (m *EmissionsGridBoundsRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *EmissionsGridBoundsRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *EmissionsGridBoundsRequest) GetDx() float32 {
	if m != nil {
		return m.Dx
	}
	return 0
}

type EmissionsGridBoundsResponse struct {
	Min                  *Point   `protobuf:"bytes,1,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Point   `protobuf:"bytes,2,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsGridBoundsResponse) Reset()         { *m = EmissionsGridBoundsResponse{} }
func (m *EmissionsGridBoundsResponse) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridBoundsResponse) ProtoMessage()    {}
func (*EmissionsGridBoundsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{10}
}
func (m *EmissionsGridBoundsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridBoundsResponse.Unmarshal(m, b)
}
func (m *EmissionsGridBoundsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridBoundsResponse.Marshal(b, m, deterministic)
}
func (dst *EmissionsGridBoundsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridBoundsResponse.Merge(dst, src)
}
func (m *EmissionsGridBoundsResponse) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridBoundsResponse.Size(m)
}
func (m *EmissionsGridBoundsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridBoundsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridBoundsResponse proto.InternalMessageInfo

func (m *EmissionsGridBoundsResponse) GetMin() *Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *EmissionsGridBoundsResponse) GetMax() *Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type EmissionsMapRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	Emission             Emission `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	SourceType           string   `protobuf:"bytes,4,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Dx                   float32  `protobuf:"fixed32,5,opt,name=Dx,proto3" json:"Dx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsMapRequest) Reset()         { *m = EmissionsMapRequest{} }
func (m *EmissionsMapRequest) String() string { return proto.CompactTextString(m) }
func (*EmissionsMapRequest) ProtoMessage()    {}
func (*EmissionsMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{11}
}
func (m *EmissionsMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsMapRequest.Unmarshal(m, b)
}
func (m *EmissionsMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsMapRequest.Marshal(b, m, deterministic)
}
func (dst *EmissionsMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsMapRequest.Merge(dst, src)
}
func (m *EmissionsMapRequest) XXX_Size() int {
	return xxx_messageInfo_EmissionsMapRequest.Size(m)
}
func (m *EmissionsMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsMapRequest proto.InternalMessageInfo

func (m *EmissionsMapRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *EmissionsMapRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

func (m *EmissionsMapRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *EmissionsMapRequest) GetDx() float32 {
	if m != nil {
		return m.Dx
	}
	return 0
}

type EmissionsMapResponse struct {
	RGB                  [][]byte `protobuf:"bytes,1,rep,name=RGB,proto3" json:"RGB,omitempty"`
	Legend               string   `protobuf:"bytes,2,opt,name=Legend,proto3" json:"Legend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsMapResponse) Reset()         { *m = EmissionsMapResponse{} }
func (m *EmissionsMapResponse) String() string { return proto.CompactTextString(m) }
func (*EmissionsMapResponse) ProtoMessage()    {}
func (*EmissionsMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{12}
}
func (m *EmissionsMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsMapResponse.Unmarshal(m, b)
}
func (m *EmissionsMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsMapResponse.Marshal(b, m, deterministic)
}
func (dst *EmissionsMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsMapResponse.Merge(dst, src)
}
func (m *EmissionsMapResponse) XXX_Size() int {
	return xxx_messageInfo_EmissionsMapResponse.Size(m)
}
func (m *EmissionsMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsMapResponse proto.InternalMessageInfo

func (m *EmissionsMapResponse) GetRGB() [][]byte {
	if m != nil {
		return m.RGB
	}
	return nil
}

func (m *EmissionsMapResponse) GetLegend() string {
	if m != nil {
		return m.Legend
	}
	return ""
}

type MapScaleRequest struct {
	CityName             string     `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	ImpactType           ImpactType `protobuf:"varint,2,opt,name=ImpactType,proto3,enum=cityaqrpc.ImpactType" json:"ImpactType,omitempty"`
	Emission             Emission   `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	SourceType           string     `protobuf:"bytes,4,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MapScaleRequest) Reset()         { *m = MapScaleRequest{} }
func (m *MapScaleRequest) String() string { return proto.CompactTextString(m) }
func (*MapScaleRequest) ProtoMessage()    {}
func (*MapScaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{13}
}
func (m *MapScaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapScaleRequest.Unmarshal(m, b)
}
func (m *MapScaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapScaleRequest.Marshal(b, m, deterministic)
}
func (dst *MapScaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapScaleRequest.Merge(dst, src)
}
func (m *MapScaleRequest) XXX_Size() int {
	return xxx_messageInfo_MapScaleRequest.Size(m)
}
func (m *MapScaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MapScaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MapScaleRequest proto.InternalMessageInfo

func (m *MapScaleRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *MapScaleRequest) GetImpactType() ImpactType {
	if m != nil {
		return m.ImpactType
	}
	return ImpactType_UNKNOWN_IMPACTTYPE
}

func (m *MapScaleRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

func (m *MapScaleRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

type MapScaleResponse struct {
	Min                  float32  `protobuf:"fixed32,1,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  float32  `protobuf:"fixed32,2,opt,name=Max,proto3" json:"Max,omitempty"`
	CutPt                float32  `protobuf:"fixed32,3,opt,name=CutPt,proto3" json:"CutPt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapScaleResponse) Reset()         { *m = MapScaleResponse{} }
func (m *MapScaleResponse) String() string { return proto.CompactTextString(m) }
func (*MapScaleResponse) ProtoMessage()    {}
func (*MapScaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_5cac49a9d9c1044f, []int{14}
}
func (m *MapScaleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapScaleResponse.Unmarshal(m, b)
}
func (m *MapScaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapScaleResponse.Marshal(b, m, deterministic)
}
func (dst *MapScaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapScaleResponse.Merge(dst, src)
}
func (m *MapScaleResponse) XXX_Size() int {
	return xxx_messageInfo_MapScaleResponse.Size(m)
}
func (m *MapScaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapScaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapScaleResponse proto.InternalMessageInfo

func (m *MapScaleResponse) GetMin() float32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *MapScaleResponse) GetMax() float32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MapScaleResponse) GetCutPt() float32 {
	if m != nil {
		return m.CutPt
	}
	return 0
}

func init() {
	proto.RegisterType((*CitiesRequest)(nil), "cityaqrpc.CitiesRequest")
	proto.RegisterType((*CitiesResponse)(nil), "cityaqrpc.CitiesResponse")
	proto.RegisterType((*CityGeometryRequest)(nil), "cityaqrpc.CityGeometryRequest")
	proto.RegisterType((*CityGeometryResponse)(nil), "cityaqrpc.CityGeometryResponse")
	proto.RegisterType((*Polygon)(nil), "cityaqrpc.Polygon")
	proto.RegisterType((*Path)(nil), "cityaqrpc.Path")
	proto.RegisterType((*Point)(nil), "cityaqrpc.Point")
	proto.RegisterType((*EmissionsGridRequest)(nil), "cityaqrpc.EmissionsGridRequest")
	proto.RegisterType((*EmissionsGridResponse)(nil), "cityaqrpc.EmissionsGridResponse")
	proto.RegisterType((*EmissionsGridBoundsRequest)(nil), "cityaqrpc.EmissionsGridBoundsRequest")
	proto.RegisterType((*EmissionsGridBoundsResponse)(nil), "cityaqrpc.EmissionsGridBoundsResponse")
	proto.RegisterType((*EmissionsMapRequest)(nil), "cityaqrpc.EmissionsMapRequest")
	proto.RegisterType((*EmissionsMapResponse)(nil), "cityaqrpc.EmissionsMapResponse")
	proto.RegisterType((*MapScaleRequest)(nil), "cityaqrpc.MapScaleRequest")
	proto.RegisterType((*MapScaleResponse)(nil), "cityaqrpc.MapScaleResponse")
	proto.RegisterEnum("cityaqrpc.Emission", Emission_name, Emission_value)
	proto.RegisterEnum("cityaqrpc.ImpactType", ImpactType_name, ImpactType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CityAQClient is the client API for CityAQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CityAQClient interface {
	Cities(ctx context.Context, in *CitiesRequest, opts ...grpc.CallOption) (*CitiesResponse, error)
	CityGeometry(ctx context.Context, in *CityGeometryRequest, opts ...grpc.CallOption) (*CityGeometryResponse, error)
	EmissionsGrid(ctx context.Context, in *EmissionsGridRequest, opts ...grpc.CallOption) (*EmissionsGridResponse, error)
	EmissionsMap(ctx context.Context, in *EmissionsMapRequest, opts ...grpc.CallOption) (*EmissionsMapResponse, error)
	EmissionsGridBounds(ctx context.Context, in *EmissionsGridBoundsRequest, opts ...grpc.CallOption) (*EmissionsGridBoundsResponse, error)
	MapScale(ctx context.Context, in *MapScaleRequest, opts ...grpc.CallOption) (*MapScaleResponse, error)
}

type cityAQClient struct {
	cc *grpc.ClientConn
}

func NewCityAQClient(cc *grpc.ClientConn) CityAQClient {
	return &cityAQClient{cc}
}

func (c *cityAQClient) Cities(ctx context.Context, in *CitiesRequest, opts ...grpc.CallOption) (*CitiesResponse, error) {
	out := new(CitiesResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/Cities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) CityGeometry(ctx context.Context, in *CityGeometryRequest, opts ...grpc.CallOption) (*CityGeometryResponse, error) {
	out := new(CityGeometryResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/CityGeometry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) EmissionsGrid(ctx context.Context, in *EmissionsGridRequest, opts ...grpc.CallOption) (*EmissionsGridResponse, error) {
	out := new(EmissionsGridResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/EmissionsGrid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) EmissionsMap(ctx context.Context, in *EmissionsMapRequest, opts ...grpc.CallOption) (*EmissionsMapResponse, error) {
	out := new(EmissionsMapResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/EmissionsMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) EmissionsGridBounds(ctx context.Context, in *EmissionsGridBoundsRequest, opts ...grpc.CallOption) (*EmissionsGridBoundsResponse, error) {
	out := new(EmissionsGridBoundsResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/EmissionsGridBounds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) MapScale(ctx context.Context, in *MapScaleRequest, opts ...grpc.CallOption) (*MapScaleResponse, error) {
	out := new(MapScaleResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/MapScale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityAQServer is the server API for CityAQ service.
type CityAQServer interface {
	Cities(context.Context, *CitiesRequest) (*CitiesResponse, error)
	CityGeometry(context.Context, *CityGeometryRequest) (*CityGeometryResponse, error)
	EmissionsGrid(context.Context, *EmissionsGridRequest) (*EmissionsGridResponse, error)
	EmissionsMap(context.Context, *EmissionsMapRequest) (*EmissionsMapResponse, error)
	EmissionsGridBounds(context.Context, *EmissionsGridBoundsRequest) (*EmissionsGridBoundsResponse, error)
	MapScale(context.Context, *MapScaleRequest) (*MapScaleResponse, error)
}

func RegisterCityAQServer(s *grpc.Server, srv CityAQServer) {
	s.RegisterService(&_CityAQ_serviceDesc, srv)
}

func _CityAQ_Cities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).Cities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/Cities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).Cities(ctx, req.(*CitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_CityGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).CityGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/CityGeometry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).CityGeometry(ctx, req.(*CityGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_EmissionsGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmissionsGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).EmissionsGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/EmissionsGrid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).EmissionsGrid(ctx, req.(*EmissionsGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_EmissionsMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmissionsMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).EmissionsMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/EmissionsMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).EmissionsMap(ctx, req.(*EmissionsMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_EmissionsGridBounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmissionsGridBoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).EmissionsGridBounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/EmissionsGridBounds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).EmissionsGridBounds(ctx, req.(*EmissionsGridBoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_MapScale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).MapScale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/MapScale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).MapScale(ctx, req.(*MapScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CityAQ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cityaqrpc.CityAQ",
	HandlerType: (*CityAQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cities",
			Handler:    _CityAQ_Cities_Handler,
		},
		{
			MethodName: "CityGeometry",
			Handler:    _CityAQ_CityGeometry_Handler,
		},
		{
			MethodName: "EmissionsGrid",
			Handler:    _CityAQ_EmissionsGrid_Handler,
		},
		{
			MethodName: "EmissionsMap",
			Handler:    _CityAQ_EmissionsMap_Handler,
		},
		{
			MethodName: "EmissionsGridBounds",
			Handler:    _CityAQ_EmissionsGridBounds_Handler,
		},
		{
			MethodName: "MapScale",
			Handler:    _CityAQ_MapScale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cityaq.proto",
}

func init() { proto.RegisterFile("cityaq.proto", fileDescriptor_cityaq_5cac49a9d9c1044f) }

var fileDescriptor_cityaq_5cac49a9d9c1044f = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5d, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x36, 0x09, 0xc9, 0x34, 0x84, 0xd5, 0x12, 0x50, 0x6a, 0x24, 0x40, 0x5b, 0x81, 0x10,
	0x0f, 0x29, 0x0d, 0xe2, 0xb9, 0x85, 0x90, 0xa6, 0x51, 0x49, 0x62, 0x36, 0x69, 0x0b, 0x4f, 0xc8,
	0x84, 0x2d, 0x58, 0x22, 0xb6, 0x89, 0x37, 0x52, 0x72, 0x8d, 0xde, 0xa5, 0x37, 0xeb, 0x01, 0x2a,
	0xaf, 0xff, 0xd6, 0x91, 0xa3, 0x46, 0x55, 0xfb, 0x36, 0xe3, 0xf9, 0x76, 0xbe, 0x6f, 0x66, 0x76,
	0xc7, 0x50, 0x1a, 0x5a, 0x7c, 0x66, 0xbe, 0xd4, 0xdc, 0xb1, 0xc3, 0x1d, 0x5c, 0x0c, 0xbc, 0xb1,
	0x3b, 0x24, 0x1b, 0xb0, 0xde, 0xb0, 0xb8, 0xc5, 0x3c, 0xca, 0x5e, 0x26, 0xcc, 0xe3, 0xe4, 0x10,
	0xca, 0xd1, 0x07, 0xcf, 0x75, 0x6c, 0x8f, 0xe1, 0x0a, 0xe4, 0xba, 0xe6, 0x88, 0x79, 0x55, 0x65,
	0x5f, 0x3b, 0x2a, 0xd2, 0xc0, 0x21, 0xef, 0x60, 0xb3, 0x61, 0xf1, 0x59, 0x8b, 0x39, 0x23, 0xc6,
	0xc7, 0xb3, 0xf0, 0x38, 0xd6, 0xa1, 0xe0, 0x7f, 0xf6, 0x31, 0x55, 0x65, 0x5f, 0x39, 0x2a, 0xd2,
	0xd8, 0x27, 0x1f, 0xa1, 0x92, 0x3e, 0x12, 0x12, 0xd4, 0xa0, 0x60, 0x38, 0xcf, 0xb3, 0x47, 0xc7,
	0x0e, 0x38, 0x5e, 0xd5, 0x71, 0x2d, 0x56, 0x58, 0x0b, 0x43, 0x34, 0xc6, 0x90, 0x13, 0x58, 0x0b,
	0x6d, 0x7c, 0x00, 0x39, 0xc3, 0xe4, 0x4f, 0xd1, 0xb9, 0x0d, 0xf9, 0x9c, 0xc9, 0x9f, 0x68, 0x10,
	0x25, 0x27, 0xb0, 0xea, 0x1b, 0xf8, 0x08, 0xf2, 0x86, 0x63, 0xd9, 0x3c, 0xc2, 0xa3, 0x14, 0x8f,
	0x65, 0x73, 0x1a, 0xc6, 0xc9, 0x1b, 0xc8, 0x09, 0x0b, 0x97, 0x40, 0xb9, 0x11, 0x95, 0xa8, 0x54,
	0xb9, 0xf1, 0xbd, 0xdb, 0xaa, 0x1a, 0x78, 0xb7, 0xe4, 0x1e, 0x2a, 0xcd, 0x91, 0xe5, 0x79, 0x96,
	0x63, 0x7b, 0xad, 0xb1, 0xf5, 0xb0, 0x44, 0x13, 0xf0, 0x2e, 0x40, 0xdf, 0x99, 0x8c, 0x87, 0x6c,
	0x30, 0x73, 0x99, 0x48, 0x55, 0xa4, 0xd2, 0x17, 0x5c, 0x06, 0xf5, 0x72, 0x5a, 0xd5, 0x04, 0x85,
	0x7a, 0x39, 0x25, 0x2d, 0xd8, 0x9a, 0xe3, 0xf8, 0xcb, 0xae, 0x3d, 0x81, 0x9e, 0x4a, 0x74, 0xe1,
	0x4c, 0xec, 0x07, 0xef, 0x7f, 0x48, 0x66, 0xb0, 0x93, 0xc9, 0x14, 0x0a, 0x27, 0xa0, 0x75, 0x2c,
	0x5b, 0xb0, 0x64, 0x4d, 0xc0, 0x0f, 0x0a, 0x8c, 0x39, 0x15, 0x5c, 0xd9, 0x18, 0x73, 0x4a, 0x7e,
	0x28, 0xb0, 0x19, 0xf3, 0x74, 0x4c, 0x77, 0x99, 0x52, 0xde, 0x42, 0x21, 0x3a, 0x22, 0x04, 0x97,
	0xeb, 0x9b, 0x52, 0xf2, 0x28, 0x44, 0x63, 0xd0, 0x5c, 0xed, 0xab, 0x0b, 0x6a, 0xcf, 0xc5, 0xb5,
	0x7f, 0x90, 0xae, 0x84, 0xd0, 0x14, 0x16, 0x8d, 0x40, 0xa3, 0xad, 0x0b, 0x31, 0xa8, 0x12, 0xf5,
	0x4d, 0xbc, 0x0d, 0xf9, 0x2b, 0xf6, 0xc8, 0xec, 0x87, 0xb0, 0xa3, 0xa1, 0x47, 0x7e, 0x2a, 0xb0,
	0xd1, 0x31, 0xdd, 0xfe, 0xd0, 0x7c, 0x66, 0xcb, 0x94, 0x74, 0x06, 0xd0, 0x1e, 0xb9, 0xe6, 0x90,
	0xc7, 0xd3, 0x29, 0xd7, 0xb7, 0xa4, 0xa2, 0x92, 0x20, 0x95, 0x80, 0xff, 0xbc, 0x13, 0xe4, 0x0a,
	0x50, 0x22, 0x3b, 0xa9, 0x3a, 0x1a, 0xb5, 0x1a, 0x0c, 0x16, 0x25, 0x83, 0x55, 0xc5, 0x18, 0xfd,
	0xf5, 0xd2, 0x98, 0x70, 0x83, 0x87, 0x17, 0x28, 0x70, 0x8e, 0x7b, 0x89, 0x3c, 0x5c, 0x01, 0xf4,
	0xa5, 0xfb, 0xb9, 0xdb, 0xfb, 0xd6, 0xbd, 0x6b, 0x76, 0xda, 0xfd, 0x7e, 0xbb, 0xd7, 0x45, 0x2b,
	0xb8, 0x08, 0x39, 0xa3, 0x53, 0xbf, 0x3b, 0x43, 0x0a, 0x5e, 0x03, 0xad, 0xfb, 0xe9, 0x14, 0xa9,
	0xc2, 0xe8, 0x4d, 0x91, 0xe6, 0x1b, 0xfd, 0xde, 0x14, 0xad, 0xfa, 0xc6, 0xd7, 0x5e, 0x03, 0xe5,
	0x8e, 0x4f, 0xe5, 0x36, 0xe1, 0x6d, 0xc0, 0x51, 0xca, 0x76, 0xc7, 0x38, 0x6f, 0x0c, 0x06, 0xb7,
	0x46, 0x13, 0xad, 0xe0, 0x75, 0x28, 0xc6, 0xe3, 0x43, 0x4a, 0xfd, 0x97, 0x06, 0x79, 0xbf, 0xd1,
	0xe7, 0xd7, 0xf8, 0xbd, 0xb0, 0x2c, 0xe6, 0xe1, 0xaa, 0xd4, 0xa7, 0xd4, 0xee, 0xd4, 0x5f, 0x67,
	0x44, 0x82, 0x4e, 0x90, 0x15, 0x7c, 0x0d, 0x25, 0x79, 0xfb, 0xe1, 0xdd, 0x34, 0x78, 0x7e, 0x93,
	0xea, 0x7b, 0x0b, 0xe3, 0x71, 0xca, 0x01, 0xac, 0xa7, 0x1e, 0x1a, 0xde, 0xcb, 0x18, 0xa1, 0xbc,
	0x99, 0xf4, 0xfd, 0xc5, 0x00, 0x59, 0xa8, 0x7c, 0x85, 0x53, 0x42, 0x33, 0xde, 0x9b, 0xbe, 0xb7,
	0x30, 0x1e, 0xa7, 0xfc, 0x2e, 0xbd, 0xd4, 0x64, 0x23, 0xe0, 0x83, 0x45, 0x6a, 0x52, 0xbb, 0x49,
	0x3f, 0xfc, 0x13, 0x2c, 0xe6, 0x69, 0x42, 0x21, 0xba, 0x83, 0x58, 0x97, 0x4e, 0xcd, 0xbd, 0x27,
	0x7d, 0x27, 0x33, 0x16, 0xa5, 0xb9, 0xcf, 0x8b, 0xdf, 0xe4, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0x1e, 0x07, 0x83, 0x36, 0x07, 0x00, 0x00,
}
