// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cityaq.proto

//+build js

package cityaqrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "github.com/johanbrandhorst/grpc-wasm"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Emission int32

const (
	Emission_UNKNOWN_EMISSION Emission = 0
	Emission_PM2_5            Emission = 1
	Emission_NH3              Emission = 2
	Emission_NOx              Emission = 3
	Emission_SOx              Emission = 4
	Emission_VOC              Emission = 5
)

var Emission_name = map[int32]string{
	0: "UNKNOWN_EMISSION",
	1: "PM2_5",
	2: "NH3",
	3: "NOx",
	4: "SOx",
	5: "VOC",
}
var Emission_value = map[string]int32{
	"UNKNOWN_EMISSION": 0,
	"PM2_5":            1,
	"NH3":              2,
	"NOx":              3,
	"SOx":              4,
	"VOC":              5,
}

func (x Emission) String() string {
	return proto.EnumName(Emission_name, int32(x))
}
func (Emission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{0}
}

type ImpactType int32

const (
	ImpactType_UNKNOWN_IMPACTTYPE ImpactType = 0
	ImpactType_Emissions          ImpactType = 1
	ImpactType_Concentrations     ImpactType = 2
)

var ImpactType_name = map[int32]string{
	0: "UNKNOWN_IMPACTTYPE",
	1: "Emissions",
	2: "Concentrations",
}
var ImpactType_value = map[string]int32{
	"UNKNOWN_IMPACTTYPE": 0,
	"Emissions":          1,
	"Concentrations":     2,
}

func (x ImpactType) String() string {
	return proto.EnumName(ImpactType_name, int32(x))
}
func (ImpactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{1}
}

type CitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CitiesRequest) Reset()         { *m = CitiesRequest{} }
func (m *CitiesRequest) String() string { return proto.CompactTextString(m) }
func (*CitiesRequest) ProtoMessage()    {}
func (*CitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{0}
}
func (m *CitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitiesRequest.Unmarshal(m, b)
}
func (m *CitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitiesRequest.Marshal(b, m, deterministic)
}
func (dst *CitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitiesRequest.Merge(dst, src)
}
func (m *CitiesRequest) XXX_Size() int {
	return xxx_messageInfo_CitiesRequest.Size(m)
}
func (m *CitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CitiesRequest proto.InternalMessageInfo

type CitiesResponse struct {
	// The names of the cities
	Names                []string `protobuf:"bytes,1,rep,name=Names,proto3" json:"Names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CitiesResponse) Reset()         { *m = CitiesResponse{} }
func (m *CitiesResponse) String() string { return proto.CompactTextString(m) }
func (*CitiesResponse) ProtoMessage()    {}
func (*CitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{1}
}
func (m *CitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitiesResponse.Unmarshal(m, b)
}
func (m *CitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitiesResponse.Marshal(b, m, deterministic)
}
func (dst *CitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitiesResponse.Merge(dst, src)
}
func (m *CitiesResponse) XXX_Size() int {
	return xxx_messageInfo_CitiesResponse.Size(m)
}
func (m *CitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CitiesResponse proto.InternalMessageInfo

func (m *CitiesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type CityGeometryRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityGeometryRequest) Reset()         { *m = CityGeometryRequest{} }
func (m *CityGeometryRequest) String() string { return proto.CompactTextString(m) }
func (*CityGeometryRequest) ProtoMessage()    {}
func (*CityGeometryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{2}
}
func (m *CityGeometryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityGeometryRequest.Unmarshal(m, b)
}
func (m *CityGeometryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityGeometryRequest.Marshal(b, m, deterministic)
}
func (dst *CityGeometryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityGeometryRequest.Merge(dst, src)
}
func (m *CityGeometryRequest) XXX_Size() int {
	return xxx_messageInfo_CityGeometryRequest.Size(m)
}
func (m *CityGeometryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CityGeometryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CityGeometryRequest proto.InternalMessageInfo

func (m *CityGeometryRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

type CityGeometryResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CityGeometryResponse) Reset()         { *m = CityGeometryResponse{} }
func (m *CityGeometryResponse) String() string { return proto.CompactTextString(m) }
func (*CityGeometryResponse) ProtoMessage()    {}
func (*CityGeometryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{3}
}
func (m *CityGeometryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityGeometryResponse.Unmarshal(m, b)
}
func (m *CityGeometryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityGeometryResponse.Marshal(b, m, deterministic)
}
func (dst *CityGeometryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityGeometryResponse.Merge(dst, src)
}
func (m *CityGeometryResponse) XXX_Size() int {
	return xxx_messageInfo_CityGeometryResponse.Size(m)
}
func (m *CityGeometryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CityGeometryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CityGeometryResponse proto.InternalMessageInfo

func (m *CityGeometryResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

type Polygon struct {
	Paths                []*Path  `protobuf:"bytes,1,rep,name=Paths,proto3" json:"Paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Polygon) Reset()         { *m = Polygon{} }
func (m *Polygon) String() string { return proto.CompactTextString(m) }
func (*Polygon) ProtoMessage()    {}
func (*Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{4}
}
func (m *Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon.Unmarshal(m, b)
}
func (m *Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon.Marshal(b, m, deterministic)
}
func (dst *Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon.Merge(dst, src)
}
func (m *Polygon) XXX_Size() int {
	return xxx_messageInfo_Polygon.Size(m)
}
func (m *Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon proto.InternalMessageInfo

func (m *Polygon) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Path struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{5}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{6}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GriddedEmissionsRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Emission             Emission `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GriddedEmissionsRequest) Reset()         { *m = GriddedEmissionsRequest{} }
func (m *GriddedEmissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GriddedEmissionsRequest) ProtoMessage()    {}
func (*GriddedEmissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{7}
}
func (m *GriddedEmissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GriddedEmissionsRequest.Unmarshal(m, b)
}
func (m *GriddedEmissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GriddedEmissionsRequest.Marshal(b, m, deterministic)
}
func (dst *GriddedEmissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GriddedEmissionsRequest.Merge(dst, src)
}
func (m *GriddedEmissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GriddedEmissionsRequest.Size(m)
}
func (m *GriddedEmissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GriddedEmissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GriddedEmissionsRequest proto.InternalMessageInfo

func (m *GriddedEmissionsRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *GriddedEmissionsRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *GriddedEmissionsRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

type GriddedEmissionsResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	Emissions            []float64  `protobuf:"fixed64,2,rep,packed,name=Emissions,proto3" json:"Emissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GriddedEmissionsResponse) Reset()         { *m = GriddedEmissionsResponse{} }
func (m *GriddedEmissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GriddedEmissionsResponse) ProtoMessage()    {}
func (*GriddedEmissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{8}
}
func (m *GriddedEmissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GriddedEmissionsResponse.Unmarshal(m, b)
}
func (m *GriddedEmissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GriddedEmissionsResponse.Marshal(b, m, deterministic)
}
func (dst *GriddedEmissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GriddedEmissionsResponse.Merge(dst, src)
}
func (m *GriddedEmissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GriddedEmissionsResponse.Size(m)
}
func (m *GriddedEmissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GriddedEmissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GriddedEmissionsResponse proto.InternalMessageInfo

func (m *GriddedEmissionsResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

func (m *GriddedEmissionsResponse) GetEmissions() []float64 {
	if m != nil {
		return m.Emissions
	}
	return nil
}

type GriddedConcentrationsRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Emission             Emission `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GriddedConcentrationsRequest) Reset()         { *m = GriddedConcentrationsRequest{} }
func (m *GriddedConcentrationsRequest) String() string { return proto.CompactTextString(m) }
func (*GriddedConcentrationsRequest) ProtoMessage()    {}
func (*GriddedConcentrationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{9}
}
func (m *GriddedConcentrationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GriddedConcentrationsRequest.Unmarshal(m, b)
}
func (m *GriddedConcentrationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GriddedConcentrationsRequest.Marshal(b, m, deterministic)
}
func (dst *GriddedConcentrationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GriddedConcentrationsRequest.Merge(dst, src)
}
func (m *GriddedConcentrationsRequest) XXX_Size() int {
	return xxx_messageInfo_GriddedConcentrationsRequest.Size(m)
}
func (m *GriddedConcentrationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GriddedConcentrationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GriddedConcentrationsRequest proto.InternalMessageInfo

func (m *GriddedConcentrationsRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *GriddedConcentrationsRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *GriddedConcentrationsRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

type GriddedConcentrationsResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	Concentrations       []float64  `protobuf:"fixed64,2,rep,packed,name=Concentrations,proto3" json:"Concentrations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GriddedConcentrationsResponse) Reset()         { *m = GriddedConcentrationsResponse{} }
func (m *GriddedConcentrationsResponse) String() string { return proto.CompactTextString(m) }
func (*GriddedConcentrationsResponse) ProtoMessage()    {}
func (*GriddedConcentrationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{10}
}
func (m *GriddedConcentrationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GriddedConcentrationsResponse.Unmarshal(m, b)
}
func (m *GriddedConcentrationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GriddedConcentrationsResponse.Marshal(b, m, deterministic)
}
func (dst *GriddedConcentrationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GriddedConcentrationsResponse.Merge(dst, src)
}
func (m *GriddedConcentrationsResponse) XXX_Size() int {
	return xxx_messageInfo_GriddedConcentrationsResponse.Size(m)
}
func (m *GriddedConcentrationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GriddedConcentrationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GriddedConcentrationsResponse proto.InternalMessageInfo

func (m *GriddedConcentrationsResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

func (m *GriddedConcentrationsResponse) GetConcentrations() []float64 {
	if m != nil {
		return m.Concentrations
	}
	return nil
}

type GriddedPopulationRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Emission             Emission `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GriddedPopulationRequest) Reset()         { *m = GriddedPopulationRequest{} }
func (m *GriddedPopulationRequest) String() string { return proto.CompactTextString(m) }
func (*GriddedPopulationRequest) ProtoMessage()    {}
func (*GriddedPopulationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{11}
}
func (m *GriddedPopulationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GriddedPopulationRequest.Unmarshal(m, b)
}
func (m *GriddedPopulationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GriddedPopulationRequest.Marshal(b, m, deterministic)
}
func (dst *GriddedPopulationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GriddedPopulationRequest.Merge(dst, src)
}
func (m *GriddedPopulationRequest) XXX_Size() int {
	return xxx_messageInfo_GriddedPopulationRequest.Size(m)
}
func (m *GriddedPopulationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GriddedPopulationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GriddedPopulationRequest proto.InternalMessageInfo

func (m *GriddedPopulationRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *GriddedPopulationRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *GriddedPopulationRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

type GriddedPopulationResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	Population           []float64  `protobuf:"fixed64,2,rep,packed,name=Population,proto3" json:"Population,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GriddedPopulationResponse) Reset()         { *m = GriddedPopulationResponse{} }
func (m *GriddedPopulationResponse) String() string { return proto.CompactTextString(m) }
func (*GriddedPopulationResponse) ProtoMessage()    {}
func (*GriddedPopulationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{12}
}
func (m *GriddedPopulationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GriddedPopulationResponse.Unmarshal(m, b)
}
func (m *GriddedPopulationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GriddedPopulationResponse.Marshal(b, m, deterministic)
}
func (dst *GriddedPopulationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GriddedPopulationResponse.Merge(dst, src)
}
func (m *GriddedPopulationResponse) XXX_Size() int {
	return xxx_messageInfo_GriddedPopulationResponse.Size(m)
}
func (m *GriddedPopulationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GriddedPopulationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GriddedPopulationResponse proto.InternalMessageInfo

func (m *GriddedPopulationResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

func (m *GriddedPopulationResponse) GetPopulation() []float64 {
	if m != nil {
		return m.Population
	}
	return nil
}

type ImpactSummaryRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Emission             Emission `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImpactSummaryRequest) Reset()         { *m = ImpactSummaryRequest{} }
func (m *ImpactSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*ImpactSummaryRequest) ProtoMessage()    {}
func (*ImpactSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{13}
}
func (m *ImpactSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImpactSummaryRequest.Unmarshal(m, b)
}
func (m *ImpactSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImpactSummaryRequest.Marshal(b, m, deterministic)
}
func (dst *ImpactSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImpactSummaryRequest.Merge(dst, src)
}
func (m *ImpactSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_ImpactSummaryRequest.Size(m)
}
func (m *ImpactSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImpactSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImpactSummaryRequest proto.InternalMessageInfo

func (m *ImpactSummaryRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *ImpactSummaryRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *ImpactSummaryRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

type ImpactSummaryResponse struct {
	// Population is the total population.
	Population float64 `protobuf:"fixed64,1,opt,name=Population,proto3" json:"Population,omitempty"`
	// CityPopulation is the total population in the city.
	CityPopulation float64 `protobuf:"fixed64,2,opt,name=CityPopulation,proto3" json:"CityPopulation,omitempty"`
	// CityExposure is the population-weighted average
	// concentration in the city.
	CityExposure float64 `protobuf:"fixed64,3,opt,name=CityExposure,proto3" json:"CityExposure,omitempty"`
	// TotalExposure is the overall population-weighted average
	// concentration.
	TotalExposure float64 `protobuf:"fixed64,4,opt,name=TotalExposure,proto3" json:"TotalExposure,omitempty"`
	// CityIF is the intake fraction in the city.
	CityIF float64 `protobuf:"fixed64,5,opt,name=CityIF,proto3" json:"CityIF,omitempty"`
	// TotalIF is the total intake fraction.
	TotalIF              float64  `protobuf:"fixed64,6,opt,name=TotalIF,proto3" json:"TotalIF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImpactSummaryResponse) Reset()         { *m = ImpactSummaryResponse{} }
func (m *ImpactSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*ImpactSummaryResponse) ProtoMessage()    {}
func (*ImpactSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{14}
}
func (m *ImpactSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImpactSummaryResponse.Unmarshal(m, b)
}
func (m *ImpactSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImpactSummaryResponse.Marshal(b, m, deterministic)
}
func (dst *ImpactSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImpactSummaryResponse.Merge(dst, src)
}
func (m *ImpactSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_ImpactSummaryResponse.Size(m)
}
func (m *ImpactSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImpactSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImpactSummaryResponse proto.InternalMessageInfo

func (m *ImpactSummaryResponse) GetPopulation() float64 {
	if m != nil {
		return m.Population
	}
	return 0
}

func (m *ImpactSummaryResponse) GetCityPopulation() float64 {
	if m != nil {
		return m.CityPopulation
	}
	return 0
}

func (m *ImpactSummaryResponse) GetCityExposure() float64 {
	if m != nil {
		return m.CityExposure
	}
	return 0
}

func (m *ImpactSummaryResponse) GetTotalExposure() float64 {
	if m != nil {
		return m.TotalExposure
	}
	return 0
}

func (m *ImpactSummaryResponse) GetCityIF() float64 {
	if m != nil {
		return m.CityIF
	}
	return 0
}

func (m *ImpactSummaryResponse) GetTotalIF() float64 {
	if m != nil {
		return m.TotalIF
	}
	return 0
}

type EmissionsGridBoundsRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	SourceType           string   `protobuf:"bytes,2,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsGridBoundsRequest) Reset()         { *m = EmissionsGridBoundsRequest{} }
func (m *EmissionsGridBoundsRequest) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridBoundsRequest) ProtoMessage()    {}
func (*EmissionsGridBoundsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{15}
}
func (m *EmissionsGridBoundsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridBoundsRequest.Unmarshal(m, b)
}
func (m *EmissionsGridBoundsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridBoundsRequest.Marshal(b, m, deterministic)
}
func (dst *EmissionsGridBoundsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridBoundsRequest.Merge(dst, src)
}
func (m *EmissionsGridBoundsRequest) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridBoundsRequest.Size(m)
}
func (m *EmissionsGridBoundsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridBoundsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridBoundsRequest proto.InternalMessageInfo

func (m *EmissionsGridBoundsRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *EmissionsGridBoundsRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

type EmissionsGridBoundsResponse struct {
	Min                  *Point   `protobuf:"bytes,1,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Point   `protobuf:"bytes,2,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsGridBoundsResponse) Reset()         { *m = EmissionsGridBoundsResponse{} }
func (m *EmissionsGridBoundsResponse) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridBoundsResponse) ProtoMessage()    {}
func (*EmissionsGridBoundsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{16}
}
func (m *EmissionsGridBoundsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridBoundsResponse.Unmarshal(m, b)
}
func (m *EmissionsGridBoundsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridBoundsResponse.Marshal(b, m, deterministic)
}
func (dst *EmissionsGridBoundsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridBoundsResponse.Merge(dst, src)
}
func (m *EmissionsGridBoundsResponse) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridBoundsResponse.Size(m)
}
func (m *EmissionsGridBoundsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridBoundsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridBoundsResponse proto.InternalMessageInfo

func (m *EmissionsGridBoundsResponse) GetMin() *Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *EmissionsGridBoundsResponse) GetMax() *Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type MapScaleRequest struct {
	CityName             string     `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	ImpactType           ImpactType `protobuf:"varint,2,opt,name=ImpactType,proto3,enum=cityaqrpc.ImpactType" json:"ImpactType,omitempty"`
	Emission             Emission   `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	SourceType           string     `protobuf:"bytes,4,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MapScaleRequest) Reset()         { *m = MapScaleRequest{} }
func (m *MapScaleRequest) String() string { return proto.CompactTextString(m) }
func (*MapScaleRequest) ProtoMessage()    {}
func (*MapScaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{17}
}
func (m *MapScaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapScaleRequest.Unmarshal(m, b)
}
func (m *MapScaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapScaleRequest.Marshal(b, m, deterministic)
}
func (dst *MapScaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapScaleRequest.Merge(dst, src)
}
func (m *MapScaleRequest) XXX_Size() int {
	return xxx_messageInfo_MapScaleRequest.Size(m)
}
func (m *MapScaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MapScaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MapScaleRequest proto.InternalMessageInfo

func (m *MapScaleRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *MapScaleRequest) GetImpactType() ImpactType {
	if m != nil {
		return m.ImpactType
	}
	return ImpactType_UNKNOWN_IMPACTTYPE
}

func (m *MapScaleRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

func (m *MapScaleRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

type MapScaleResponse struct {
	Min                  float64  `protobuf:"fixed64,1,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  float64  `protobuf:"fixed64,2,opt,name=Max,proto3" json:"Max,omitempty"`
	CutPt                float64  `protobuf:"fixed64,3,opt,name=CutPt,proto3" json:"CutPt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapScaleResponse) Reset()         { *m = MapScaleResponse{} }
func (m *MapScaleResponse) String() string { return proto.CompactTextString(m) }
func (*MapScaleResponse) ProtoMessage()    {}
func (*MapScaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cityaq_f793410a600d19a7, []int{18}
}
func (m *MapScaleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapScaleResponse.Unmarshal(m, b)
}
func (m *MapScaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapScaleResponse.Marshal(b, m, deterministic)
}
func (dst *MapScaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapScaleResponse.Merge(dst, src)
}
func (m *MapScaleResponse) XXX_Size() int {
	return xxx_messageInfo_MapScaleResponse.Size(m)
}
func (m *MapScaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapScaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapScaleResponse proto.InternalMessageInfo

func (m *MapScaleResponse) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *MapScaleResponse) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MapScaleResponse) GetCutPt() float64 {
	if m != nil {
		return m.CutPt
	}
	return 0
}

func init() {
	proto.RegisterType((*CitiesRequest)(nil), "cityaqrpc.CitiesRequest")
	proto.RegisterType((*CitiesResponse)(nil), "cityaqrpc.CitiesResponse")
	proto.RegisterType((*CityGeometryRequest)(nil), "cityaqrpc.CityGeometryRequest")
	proto.RegisterType((*CityGeometryResponse)(nil), "cityaqrpc.CityGeometryResponse")
	proto.RegisterType((*Polygon)(nil), "cityaqrpc.Polygon")
	proto.RegisterType((*Path)(nil), "cityaqrpc.Path")
	proto.RegisterType((*Point)(nil), "cityaqrpc.Point")
	proto.RegisterType((*GriddedEmissionsRequest)(nil), "cityaqrpc.GriddedEmissionsRequest")
	proto.RegisterType((*GriddedEmissionsResponse)(nil), "cityaqrpc.GriddedEmissionsResponse")
	proto.RegisterType((*GriddedConcentrationsRequest)(nil), "cityaqrpc.GriddedConcentrationsRequest")
	proto.RegisterType((*GriddedConcentrationsResponse)(nil), "cityaqrpc.GriddedConcentrationsResponse")
	proto.RegisterType((*GriddedPopulationRequest)(nil), "cityaqrpc.GriddedPopulationRequest")
	proto.RegisterType((*GriddedPopulationResponse)(nil), "cityaqrpc.GriddedPopulationResponse")
	proto.RegisterType((*ImpactSummaryRequest)(nil), "cityaqrpc.ImpactSummaryRequest")
	proto.RegisterType((*ImpactSummaryResponse)(nil), "cityaqrpc.ImpactSummaryResponse")
	proto.RegisterType((*EmissionsGridBoundsRequest)(nil), "cityaqrpc.EmissionsGridBoundsRequest")
	proto.RegisterType((*EmissionsGridBoundsResponse)(nil), "cityaqrpc.EmissionsGridBoundsResponse")
	proto.RegisterType((*MapScaleRequest)(nil), "cityaqrpc.MapScaleRequest")
	proto.RegisterType((*MapScaleResponse)(nil), "cityaqrpc.MapScaleResponse")
	proto.RegisterEnum("cityaqrpc.Emission", Emission_name, Emission_value)
	proto.RegisterEnum("cityaqrpc.ImpactType", ImpactType_name, ImpactType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CityAQClient is the client API for CityAQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CityAQClient interface {
	// Cities returns the available cities.
	Cities(ctx context.Context, in *CitiesRequest, opts ...grpc.CallOption) (*CitiesResponse, error)
	// CityGeometry returns the boundary of the specified city.
	CityGeometry(ctx context.Context, in *CityGeometryRequest, opts ...grpc.CallOption) (*CityGeometryResponse, error)
	// GriddedEmissions returns the distribution within the city of
	// 1 kilotonne of emissions.
	GriddedEmissions(ctx context.Context, in *GriddedEmissionsRequest, opts ...grpc.CallOption) (*GriddedEmissionsResponse, error)
	// EmissionsGridBounds returns the bounds of the grid used in GriddedEmissions.
	EmissionsGridBounds(ctx context.Context, in *EmissionsGridBoundsRequest, opts ...grpc.CallOption) (*EmissionsGridBoundsResponse, error)
	// GriddedConcentrations returns the concentrations resulting from the
	// corresponding GriddedEmissions.
	GriddedConcentrations(ctx context.Context, in *GriddedConcentrationsRequest, opts ...grpc.CallOption) (*GriddedConcentrationsResponse, error)
	// MapScale returns the minimum and maximum values of the result
	// of the given request.
	MapScale(ctx context.Context, in *MapScaleRequest, opts ...grpc.CallOption) (*MapScaleResponse, error)
	// GriddedPopulation returns the population counts---gridded to the
	// concentration grid---associated with the given request.
	GriddedPopulation(ctx context.Context, in *GriddedPopulationRequest, opts ...grpc.CallOption) (*GriddedPopulationResponse, error)
	// ImpactSummary returns a summary of the impacts from the given request.
	ImpactSummary(ctx context.Context, in *ImpactSummaryRequest, opts ...grpc.CallOption) (*ImpactSummaryResponse, error)
}

type cityAQClient struct {
	cc *grpc.ClientConn
}

func NewCityAQClient(cc *grpc.ClientConn) CityAQClient {
	return &cityAQClient{cc}
}

func (c *cityAQClient) Cities(ctx context.Context, in *CitiesRequest, opts ...grpc.CallOption) (*CitiesResponse, error) {
	out := new(CitiesResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/Cities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) CityGeometry(ctx context.Context, in *CityGeometryRequest, opts ...grpc.CallOption) (*CityGeometryResponse, error) {
	out := new(CityGeometryResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/CityGeometry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) GriddedEmissions(ctx context.Context, in *GriddedEmissionsRequest, opts ...grpc.CallOption) (*GriddedEmissionsResponse, error) {
	out := new(GriddedEmissionsResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/GriddedEmissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) EmissionsGridBounds(ctx context.Context, in *EmissionsGridBoundsRequest, opts ...grpc.CallOption) (*EmissionsGridBoundsResponse, error) {
	out := new(EmissionsGridBoundsResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/EmissionsGridBounds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) GriddedConcentrations(ctx context.Context, in *GriddedConcentrationsRequest, opts ...grpc.CallOption) (*GriddedConcentrationsResponse, error) {
	out := new(GriddedConcentrationsResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/GriddedConcentrations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) MapScale(ctx context.Context, in *MapScaleRequest, opts ...grpc.CallOption) (*MapScaleResponse, error) {
	out := new(MapScaleResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/MapScale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) GriddedPopulation(ctx context.Context, in *GriddedPopulationRequest, opts ...grpc.CallOption) (*GriddedPopulationResponse, error) {
	out := new(GriddedPopulationResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/GriddedPopulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) ImpactSummary(ctx context.Context, in *ImpactSummaryRequest, opts ...grpc.CallOption) (*ImpactSummaryResponse, error) {
	out := new(ImpactSummaryResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/ImpactSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityAQServer is the server API for CityAQ service.
type CityAQServer interface {
	// Cities returns the available cities.
	Cities(context.Context, *CitiesRequest) (*CitiesResponse, error)
	// CityGeometry returns the boundary of the specified city.
	CityGeometry(context.Context, *CityGeometryRequest) (*CityGeometryResponse, error)
	// GriddedEmissions returns the distribution within the city of
	// 1 kilotonne of emissions.
	GriddedEmissions(context.Context, *GriddedEmissionsRequest) (*GriddedEmissionsResponse, error)
	// EmissionsGridBounds returns the bounds of the grid used in GriddedEmissions.
	EmissionsGridBounds(context.Context, *EmissionsGridBoundsRequest) (*EmissionsGridBoundsResponse, error)
	// GriddedConcentrations returns the concentrations resulting from the
	// corresponding GriddedEmissions.
	GriddedConcentrations(context.Context, *GriddedConcentrationsRequest) (*GriddedConcentrationsResponse, error)
	// MapScale returns the minimum and maximum values of the result
	// of the given request.
	MapScale(context.Context, *MapScaleRequest) (*MapScaleResponse, error)
	// GriddedPopulation returns the population counts---gridded to the
	// concentration grid---associated with the given request.
	GriddedPopulation(context.Context, *GriddedPopulationRequest) (*GriddedPopulationResponse, error)
	// ImpactSummary returns a summary of the impacts from the given request.
	ImpactSummary(context.Context, *ImpactSummaryRequest) (*ImpactSummaryResponse, error)
}

func RegisterCityAQServer(s *grpc.Server, srv CityAQServer) {
	s.RegisterService(&_CityAQ_serviceDesc, srv)
}

func _CityAQ_Cities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).Cities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/Cities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).Cities(ctx, req.(*CitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_CityGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).CityGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/CityGeometry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).CityGeometry(ctx, req.(*CityGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_GriddedEmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GriddedEmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).GriddedEmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/GriddedEmissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).GriddedEmissions(ctx, req.(*GriddedEmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_EmissionsGridBounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmissionsGridBoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).EmissionsGridBounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/EmissionsGridBounds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).EmissionsGridBounds(ctx, req.(*EmissionsGridBoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_GriddedConcentrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GriddedConcentrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).GriddedConcentrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/GriddedConcentrations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).GriddedConcentrations(ctx, req.(*GriddedConcentrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_MapScale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).MapScale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/MapScale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).MapScale(ctx, req.(*MapScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_GriddedPopulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GriddedPopulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).GriddedPopulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/GriddedPopulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).GriddedPopulation(ctx, req.(*GriddedPopulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_ImpactSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpactSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).ImpactSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/ImpactSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).ImpactSummary(ctx, req.(*ImpactSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CityAQ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cityaqrpc.CityAQ",
	HandlerType: (*CityAQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cities",
			Handler:    _CityAQ_Cities_Handler,
		},
		{
			MethodName: "CityGeometry",
			Handler:    _CityAQ_CityGeometry_Handler,
		},
		{
			MethodName: "GriddedEmissions",
			Handler:    _CityAQ_GriddedEmissions_Handler,
		},
		{
			MethodName: "EmissionsGridBounds",
			Handler:    _CityAQ_EmissionsGridBounds_Handler,
		},
		{
			MethodName: "GriddedConcentrations",
			Handler:    _CityAQ_GriddedConcentrations_Handler,
		},
		{
			MethodName: "MapScale",
			Handler:    _CityAQ_MapScale_Handler,
		},
		{
			MethodName: "GriddedPopulation",
			Handler:    _CityAQ_GriddedPopulation_Handler,
		},
		{
			MethodName: "ImpactSummary",
			Handler:    _CityAQ_ImpactSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cityaq.proto",
}

func init() { proto.RegisterFile("cityaq.proto", fileDescriptor_cityaq_f793410a600d19a7) }

var fileDescriptor_cityaq_f793410a600d19a7 = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdb, 0x4e, 0xf3, 0x46,
	0x10, 0x66, 0x73, 0x22, 0x99, 0x9f, 0x80, 0x3b, 0x84, 0xbf, 0xfe, 0x0d, 0x85, 0x68, 0x39, 0x34,
	0xe2, 0x22, 0xa5, 0x41, 0x5c, 0x57, 0x10, 0x05, 0x1a, 0xb5, 0x49, 0x8c, 0x93, 0xb6, 0x50, 0xa9,
	0xa2, 0x6e, 0xe2, 0x16, 0xab, 0x89, 0x6d, 0xe2, 0x8d, 0x9a, 0x5c, 0x57, 0x6a, 0x2f, 0xfa, 0x3c,
	0x7d, 0x8f, 0xde, 0xf7, 0x65, 0x2a, 0xaf, 0xcf, 0x89, 0x03, 0x14, 0x21, 0x71, 0xb7, 0x33, 0xf3,
	0xcd, 0xe9, 0xf3, 0xce, 0x8e, 0x61, 0xad, 0xaf, 0xb3, 0x99, 0xfa, 0x50, 0xb5, 0xc6, 0x26, 0x33,
	0xb1, 0xe0, 0x4a, 0x63, 0xab, 0x4f, 0x37, 0xa0, 0x58, 0xd7, 0x99, 0xae, 0xd9, 0x8a, 0xf6, 0x30,
	0xd1, 0x6c, 0x46, 0x8f, 0x60, 0xdd, 0x57, 0xd8, 0x96, 0x69, 0xd8, 0x1a, 0x96, 0x20, 0xdb, 0x56,
	0x47, 0x9a, 0x2d, 0x92, 0x72, 0xba, 0x52, 0x50, 0x5c, 0x81, 0x7e, 0x0e, 0x9b, 0x75, 0x9d, 0xcd,
	0xae, 0x34, 0x73, 0xa4, 0xb1, 0xf1, 0xcc, 0x73, 0x47, 0x09, 0xf2, 0x8e, 0xda, 0xc1, 0x88, 0xa4,
	0x4c, 0x2a, 0x05, 0x25, 0x90, 0xe9, 0x25, 0x94, 0xe2, 0x2e, 0x5e, 0x82, 0x2a, 0xe4, 0x65, 0x73,
	0x38, 0xfb, 0xc5, 0x34, 0xdc, 0x1c, 0xef, 0x6a, 0x58, 0x0d, 0x2a, 0xac, 0x7a, 0x26, 0x25, 0xc0,
	0xd0, 0x13, 0x58, 0xf5, 0xce, 0x78, 0x08, 0x59, 0x59, 0x65, 0xf7, 0xbe, 0xdf, 0x46, 0xd4, 0x4f,
	0x65, 0xf7, 0x8a, 0x6b, 0xa5, 0x27, 0x90, 0x71, 0x0e, 0x58, 0x81, 0x9c, 0x6c, 0xea, 0x06, 0xf3,
	0xf1, 0x42, 0x2c, 0x8f, 0x6e, 0x30, 0xc5, 0xb3, 0xd3, 0x7d, 0xc8, 0xf2, 0x13, 0xae, 0x01, 0xb9,
	0xe1, 0x9d, 0x10, 0x85, 0xdc, 0x38, 0xd2, 0xad, 0x98, 0x72, 0xa5, 0x5b, 0xfa, 0x07, 0x81, 0x8f,
	0xaf, 0xc6, 0xfa, 0x60, 0xa0, 0x0d, 0x1a, 0x23, 0xdd, 0xb6, 0x75, 0xd3, 0xb0, 0x9f, 0x41, 0x04,
	0xee, 0x02, 0x74, 0xcd, 0xc9, 0xb8, 0xaf, 0xf5, 0x66, 0x96, 0xc6, 0xc3, 0x15, 0x94, 0x88, 0x06,
	0x3f, 0x83, 0xbc, 0x1f, 0x4f, 0x4c, 0x97, 0x49, 0x65, 0xbd, 0xb6, 0x19, 0x29, 0xd4, 0x37, 0x29,
	0x01, 0x88, 0xde, 0x83, 0xb8, 0x58, 0xc7, 0xcb, 0xd8, 0xc5, 0x1d, 0x28, 0x04, 0x41, 0xc4, 0x54,
	0x39, 0x5d, 0x21, 0x4a, 0xa8, 0xa0, 0x7f, 0x11, 0xd8, 0xf1, 0x52, 0xd5, 0x4d, 0xa3, 0xaf, 0x19,
	0x6c, 0xac, 0xb2, 0x37, 0xeb, 0xfb, 0x37, 0xf8, 0x64, 0x49, 0x31, 0x2f, 0x6c, 0xde, 0xb9, 0xfd,
	0xb1, 0x48, 0x1e, 0x03, 0x73, 0x5a, 0xfa, 0x27, 0x09, 0x18, 0x97, 0x4d, 0x6b, 0x32, 0xe4, 0xea,
	0x37, 0xa1, 0xe0, 0x57, 0xf8, 0x90, 0x50, 0xc8, 0x0b, 0xdb, 0xdf, 0x05, 0x08, 0xa3, 0x78, 0xad,
	0x47, 0x34, 0xf4, 0x77, 0x02, 0xa5, 0xe6, 0xc8, 0x52, 0xfb, 0xac, 0x3b, 0x19, 0x8d, 0xd4, 0x67,
	0x8d, 0xfd, 0xeb, 0xb7, 0xfc, 0x2f, 0x81, 0xad, 0xb9, 0x2a, 0xbc, 0x7e, 0xe3, 0xf5, 0xbb, 0x53,
	0x1b, 0xd1, 0xa0, 0xfb, 0xb8, 0xcd, 0x62, 0x3d, 0x12, 0xfe, 0x79, 0x63, 0x5a, 0xa4, 0xb0, 0xe6,
	0x68, 0x1a, 0x53, 0xcb, 0xb4, 0x27, 0x63, 0x8d, 0x97, 0x45, 0x94, 0x98, 0x0e, 0x0f, 0xa0, 0xd8,
	0x33, 0x99, 0x3a, 0x0c, 0x40, 0x19, 0x0e, 0x8a, 0x2b, 0xf1, 0x3d, 0xe4, 0x1c, 0xaf, 0xe6, 0xa5,
	0x98, 0xe5, 0x66, 0x4f, 0x42, 0x11, 0x56, 0x39, 0xb0, 0x79, 0x29, 0xe6, 0xb8, 0xc1, 0x17, 0xe9,
	0x0d, 0x48, 0xc1, 0xb8, 0x39, 0x5f, 0xf6, 0xc2, 0x9c, 0x18, 0x83, 0xd7, 0x18, 0x2f, 0xaa, 0xc1,
	0x76, 0x62, 0x64, 0x8f, 0x3c, 0x0a, 0xe9, 0x96, 0xee, 0xb2, 0x96, 0xf4, 0x32, 0x3a, 0x46, 0x8e,
	0x51, 0xa7, 0x3c, 0x76, 0x32, 0x46, 0x9d, 0xd2, 0xbf, 0x09, 0x6c, 0xb4, 0x54, 0xab, 0xdb, 0x57,
	0x87, 0xda, 0x73, 0xca, 0x3e, 0x03, 0x70, 0xbf, 0x66, 0x50, 0xf6, 0x7a, 0x6d, 0x2b, 0x12, 0x3a,
	0x34, 0x2a, 0x11, 0xe0, 0xff, 0xbe, 0x36, 0x73, 0xf4, 0x64, 0x16, 0xe8, 0xf9, 0x1a, 0x84, 0xb0,
	0x6c, 0x8f, 0x13, 0x21, 0xe4, 0x84, 0xb8, 0x0c, 0x08, 0x21, 0x03, 0x84, 0xf7, 0xeb, 0xec, 0xc7,
	0xfa, 0x84, 0xc9, 0xcc, 0xbb, 0x25, 0xae, 0x70, 0xdc, 0x09, 0xcb, 0xc3, 0x12, 0x08, 0xdf, 0xb4,
	0xbf, 0x6a, 0x77, 0xbe, 0x6b, 0xdf, 0x35, 0x5a, 0xcd, 0x6e, 0xb7, 0xd9, 0x69, 0x0b, 0x2b, 0x58,
	0x80, 0xac, 0xdc, 0xaa, 0xdd, 0x9d, 0x09, 0x04, 0x57, 0x21, 0xdd, 0xfe, 0xf2, 0x54, 0x48, 0xf1,
	0x43, 0x67, 0x2a, 0xa4, 0x9d, 0x43, 0xb7, 0x33, 0x15, 0x32, 0xce, 0xe1, 0xdb, 0x4e, 0x5d, 0xc8,
	0x1e, 0x5f, 0x45, 0x69, 0xc2, 0xf7, 0x80, 0x7e, 0xc8, 0x66, 0x4b, 0x3e, 0xaf, 0xf7, 0x7a, 0xb7,
	0x72, 0x43, 0x58, 0xc1, 0x62, 0xe4, 0xf5, 0x16, 0x08, 0xe2, 0xfc, 0x7b, 0x26, 0xa4, 0x6a, 0xff,
	0x64, 0xdd, 0x3b, 0x79, 0x7e, 0x8d, 0x5f, 0xf0, 0x93, 0xae, 0xd9, 0x28, 0x46, 0xb8, 0x8b, 0xfd,
	0x10, 0x48, 0x1f, 0x12, 0x2c, 0x2e, 0x3b, 0x74, 0x05, 0xaf, 0xdd, 0x41, 0xf1, 0x57, 0x3a, 0xee,
	0xc6, 0xc1, 0xf3, 0xbf, 0x07, 0xd2, 0xde, 0x52, 0x7b, 0x10, 0xf2, 0x07, 0x10, 0xe6, 0x77, 0x19,
	0xd2, 0x88, 0xdb, 0x92, 0x85, 0x2b, 0xed, 0x3f, 0x8a, 0x09, 0xc2, 0xff, 0x0c, 0x9b, 0x09, 0x43,
	0x80, 0x87, 0x09, 0x77, 0x67, 0x71, 0xfc, 0xa4, 0xa3, 0xa7, 0x60, 0x41, 0x9e, 0x21, 0x6c, 0x25,
	0xae, 0x26, 0xfc, 0x74, 0xb1, 0xce, 0xc4, 0x4d, 0x2a, 0x55, 0x9e, 0x06, 0x06, 0xd9, 0x1a, 0x90,
	0xf7, 0xef, 0x2e, 0x4a, 0x11, 0xbf, 0xb9, 0x39, 0x94, 0xb6, 0x13, 0x6d, 0x41, 0x98, 0x1f, 0xe1,
	0xa3, 0x85, 0x65, 0x82, 0x09, 0xc4, 0x2e, 0xec, 0x3c, 0xe9, 0xe0, 0x71, 0x50, 0x90, 0xa1, 0x07,
	0xc5, 0xd8, 0xd3, 0x8d, 0x7b, 0x0b, 0x93, 0x1e, 0x5f, 0x2d, 0x52, 0x79, 0x39, 0xc0, 0x8f, 0x7a,
	0xf1, 0xee, 0xfb, 0xf0, 0x97, 0xf6, 0xa7, 0x1c, 0xff, 0xc9, 0x3d, 0xfd, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0xb3, 0xf9, 0x83, 0xf4, 0x0a, 0x00, 0x00,
}
