// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cityaq.proto

package cityaqrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Emission int32

const (
	Emission_UNKNOWN_EMISSION Emission = 0
	Emission_PM2_5            Emission = 1
	Emission_NH3              Emission = 2
	Emission_NOx              Emission = 3
	Emission_SOx              Emission = 4
	Emission_VOC              Emission = 5
)

var Emission_name = map[int32]string{
	0: "UNKNOWN_EMISSION",
	1: "PM2_5",
	2: "NH3",
	3: "NOx",
	4: "SOx",
	5: "VOC",
}

var Emission_value = map[string]int32{
	"UNKNOWN_EMISSION": 0,
	"PM2_5":            1,
	"NH3":              2,
	"NOx":              3,
	"SOx":              4,
	"VOC":              5,
}

func (x Emission) String() string {
	return proto.EnumName(Emission_name, int32(x))
}

func (Emission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{0}
}

type CitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CitiesRequest) Reset()         { *m = CitiesRequest{} }
func (m *CitiesRequest) String() string { return proto.CompactTextString(m) }
func (*CitiesRequest) ProtoMessage()    {}
func (*CitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{0}
}

func (m *CitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitiesRequest.Unmarshal(m, b)
}
func (m *CitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitiesRequest.Marshal(b, m, deterministic)
}
func (m *CitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitiesRequest.Merge(m, src)
}
func (m *CitiesRequest) XXX_Size() int {
	return xxx_messageInfo_CitiesRequest.Size(m)
}
func (m *CitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CitiesRequest proto.InternalMessageInfo

type CitiesResponse struct {
	// The names of the cities
	Names []string `protobuf:"bytes,1,rep,name=Names,proto3" json:"Names,omitempty"`
	// Paths to the file containing the geometry of each city.
	Paths                []string `protobuf:"bytes,2,rep,name=Paths,proto3" json:"Paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CitiesResponse) Reset()         { *m = CitiesResponse{} }
func (m *CitiesResponse) String() string { return proto.CompactTextString(m) }
func (*CitiesResponse) ProtoMessage()    {}
func (*CitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{1}
}

func (m *CitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitiesResponse.Unmarshal(m, b)
}
func (m *CitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitiesResponse.Marshal(b, m, deterministic)
}
func (m *CitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitiesResponse.Merge(m, src)
}
func (m *CitiesResponse) XXX_Size() int {
	return xxx_messageInfo_CitiesResponse.Size(m)
}
func (m *CitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CitiesResponse proto.InternalMessageInfo

func (m *CitiesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *CitiesResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type CityGeometryRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityGeometryRequest) Reset()         { *m = CityGeometryRequest{} }
func (m *CityGeometryRequest) String() string { return proto.CompactTextString(m) }
func (*CityGeometryRequest) ProtoMessage()    {}
func (*CityGeometryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{2}
}

func (m *CityGeometryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityGeometryRequest.Unmarshal(m, b)
}
func (m *CityGeometryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityGeometryRequest.Marshal(b, m, deterministic)
}
func (m *CityGeometryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityGeometryRequest.Merge(m, src)
}
func (m *CityGeometryRequest) XXX_Size() int {
	return xxx_messageInfo_CityGeometryRequest.Size(m)
}
func (m *CityGeometryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CityGeometryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CityGeometryRequest proto.InternalMessageInfo

func (m *CityGeometryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type CityGeometryResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CityGeometryResponse) Reset()         { *m = CityGeometryResponse{} }
func (m *CityGeometryResponse) String() string { return proto.CompactTextString(m) }
func (*CityGeometryResponse) ProtoMessage()    {}
func (*CityGeometryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{3}
}

func (m *CityGeometryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityGeometryResponse.Unmarshal(m, b)
}
func (m *CityGeometryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityGeometryResponse.Marshal(b, m, deterministic)
}
func (m *CityGeometryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityGeometryResponse.Merge(m, src)
}
func (m *CityGeometryResponse) XXX_Size() int {
	return xxx_messageInfo_CityGeometryResponse.Size(m)
}
func (m *CityGeometryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CityGeometryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CityGeometryResponse proto.InternalMessageInfo

func (m *CityGeometryResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

type Polygon struct {
	Paths                []*Path  `protobuf:"bytes,1,rep,name=Paths,proto3" json:"Paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Polygon) Reset()         { *m = Polygon{} }
func (m *Polygon) String() string { return proto.CompactTextString(m) }
func (*Polygon) ProtoMessage()    {}
func (*Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{4}
}

func (m *Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon.Unmarshal(m, b)
}
func (m *Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon.Marshal(b, m, deterministic)
}
func (m *Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon.Merge(m, src)
}
func (m *Polygon) XXX_Size() int {
	return xxx_messageInfo_Polygon.Size(m)
}
func (m *Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon proto.InternalMessageInfo

func (m *Polygon) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Path struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{5}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{6}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type EmissionsGridRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsGridRequest) Reset()         { *m = EmissionsGridRequest{} }
func (m *EmissionsGridRequest) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridRequest) ProtoMessage()    {}
func (*EmissionsGridRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{7}
}

func (m *EmissionsGridRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridRequest.Unmarshal(m, b)
}
func (m *EmissionsGridRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridRequest.Marshal(b, m, deterministic)
}
func (m *EmissionsGridRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridRequest.Merge(m, src)
}
func (m *EmissionsGridRequest) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridRequest.Size(m)
}
func (m *EmissionsGridRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridRequest proto.InternalMessageInfo

func (m *EmissionsGridRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *EmissionsGridRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type EmissionsGridResponse struct {
	Polygons             []*Polygon `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EmissionsGridResponse) Reset()         { *m = EmissionsGridResponse{} }
func (m *EmissionsGridResponse) String() string { return proto.CompactTextString(m) }
func (*EmissionsGridResponse) ProtoMessage()    {}
func (*EmissionsGridResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{8}
}

func (m *EmissionsGridResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsGridResponse.Unmarshal(m, b)
}
func (m *EmissionsGridResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsGridResponse.Marshal(b, m, deterministic)
}
func (m *EmissionsGridResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsGridResponse.Merge(m, src)
}
func (m *EmissionsGridResponse) XXX_Size() int {
	return xxx_messageInfo_EmissionsGridResponse.Size(m)
}
func (m *EmissionsGridResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsGridResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsGridResponse proto.InternalMessageInfo

func (m *EmissionsGridResponse) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

type EmissionsMapRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=CityName,proto3" json:"CityName,omitempty"`
	CityPath             string   `protobuf:"bytes,2,opt,name=CityPath,proto3" json:"CityPath,omitempty"`
	Emission             Emission `protobuf:"varint,3,opt,name=Emission,proto3,enum=cityaqrpc.Emission" json:"Emission,omitempty"`
	SourceType           string   `protobuf:"bytes,4,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsMapRequest) Reset()         { *m = EmissionsMapRequest{} }
func (m *EmissionsMapRequest) String() string { return proto.CompactTextString(m) }
func (*EmissionsMapRequest) ProtoMessage()    {}
func (*EmissionsMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{9}
}

func (m *EmissionsMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsMapRequest.Unmarshal(m, b)
}
func (m *EmissionsMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsMapRequest.Marshal(b, m, deterministic)
}
func (m *EmissionsMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsMapRequest.Merge(m, src)
}
func (m *EmissionsMapRequest) XXX_Size() int {
	return xxx_messageInfo_EmissionsMapRequest.Size(m)
}
func (m *EmissionsMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsMapRequest proto.InternalMessageInfo

func (m *EmissionsMapRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *EmissionsMapRequest) GetCityPath() string {
	if m != nil {
		return m.CityPath
	}
	return ""
}

func (m *EmissionsMapRequest) GetEmission() Emission {
	if m != nil {
		return m.Emission
	}
	return Emission_UNKNOWN_EMISSION
}

func (m *EmissionsMapRequest) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

type EmissionsMapResponse struct {
	RGB                  [][]byte `protobuf:"bytes,1,rep,name=RGB,proto3" json:"RGB,omitempty"`
	Legend               string   `protobuf:"bytes,2,opt,name=Legend,proto3" json:"Legend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmissionsMapResponse) Reset()         { *m = EmissionsMapResponse{} }
func (m *EmissionsMapResponse) String() string { return proto.CompactTextString(m) }
func (*EmissionsMapResponse) ProtoMessage()    {}
func (*EmissionsMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cccf5bb3409f35d, []int{10}
}

func (m *EmissionsMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmissionsMapResponse.Unmarshal(m, b)
}
func (m *EmissionsMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmissionsMapResponse.Marshal(b, m, deterministic)
}
func (m *EmissionsMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionsMapResponse.Merge(m, src)
}
func (m *EmissionsMapResponse) XXX_Size() int {
	return xxx_messageInfo_EmissionsMapResponse.Size(m)
}
func (m *EmissionsMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionsMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionsMapResponse proto.InternalMessageInfo

func (m *EmissionsMapResponse) GetRGB() [][]byte {
	if m != nil {
		return m.RGB
	}
	return nil
}

func (m *EmissionsMapResponse) GetLegend() string {
	if m != nil {
		return m.Legend
	}
	return ""
}

func init() {
	proto.RegisterEnum("cityaqrpc.Emission", Emission_name, Emission_value)
	proto.RegisterType((*CitiesRequest)(nil), "cityaqrpc.CitiesRequest")
	proto.RegisterType((*CitiesResponse)(nil), "cityaqrpc.CitiesResponse")
	proto.RegisterType((*CityGeometryRequest)(nil), "cityaqrpc.CityGeometryRequest")
	proto.RegisterType((*CityGeometryResponse)(nil), "cityaqrpc.CityGeometryResponse")
	proto.RegisterType((*Polygon)(nil), "cityaqrpc.Polygon")
	proto.RegisterType((*Path)(nil), "cityaqrpc.Path")
	proto.RegisterType((*Point)(nil), "cityaqrpc.Point")
	proto.RegisterType((*EmissionsGridRequest)(nil), "cityaqrpc.EmissionsGridRequest")
	proto.RegisterType((*EmissionsGridResponse)(nil), "cityaqrpc.EmissionsGridResponse")
	proto.RegisterType((*EmissionsMapRequest)(nil), "cityaqrpc.EmissionsMapRequest")
	proto.RegisterType((*EmissionsMapResponse)(nil), "cityaqrpc.EmissionsMapResponse")
}

func init() { proto.RegisterFile("cityaq.proto", fileDescriptor_7cccf5bb3409f35d) }

var fileDescriptor_7cccf5bb3409f35d = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0x26, 0x4d, 0x86, 0xb4, 0xb5, 0x26, 0x01, 0x19, 0x1f, 0x9a, 0xc8, 0x08, 0x29,
	0x70, 0x08, 0x55, 0x2a, 0x6e, 0x48, 0x7c, 0x44, 0x25, 0x54, 0x10, 0x3b, 0x75, 0x0a, 0xb4, 0xa7,
	0xca, 0xa4, 0xab, 0x76, 0x25, 0x62, 0xbb, 0xde, 0xad, 0x54, 0xff, 0x19, 0xfe, 0x0d, 0xff, 0x0b,
	0xed, 0x7a, 0x6d, 0xd6, 0x55, 0x22, 0x21, 0x6e, 0xef, 0xed, 0x1b, 0xcf, 0xbe, 0x37, 0x1e, 0x1b,
	0x3a, 0x4b, 0xca, 0xf3, 0xe8, 0x76, 0x94, 0x66, 0x09, 0x4f, 0xb0, 0x5d, 0xb0, 0x2c, 0x5d, 0x7a,
	0xfb, 0xb0, 0x3b, 0xa1, 0x9c, 0x12, 0x16, 0x92, 0xdb, 0x3b, 0xc2, 0xb8, 0xf7, 0x06, 0xf6, 0xca,
	0x03, 0x96, 0x26, 0x31, 0x23, 0xd8, 0x83, 0x86, 0x1f, 0xad, 0x08, 0x73, 0x8c, 0x81, 0x35, 0x6c,
	0x87, 0x05, 0x11, 0xa7, 0xf3, 0x88, 0xdf, 0x30, 0xc7, 0x2c, 0x4e, 0x25, 0xf1, 0x5e, 0x40, 0x77,
	0x42, 0x79, 0x3e, 0x25, 0xc9, 0x8a, 0xf0, 0x2c, 0x57, 0x4d, 0x11, 0x61, 0x5b, 0xe8, 0x8e, 0x31,
	0x30, 0x86, 0xed, 0x50, 0x62, 0xef, 0x23, 0xf4, 0xea, 0xa5, 0xea, 0xba, 0x11, 0xb4, 0xe6, 0xc9,
	0xcf, 0xfc, 0x3a, 0x89, 0x8b, 0x1b, 0x1f, 0x8d, 0x71, 0x54, 0xf9, 0x1d, 0x29, 0x29, 0xac, 0x6a,
	0xbc, 0x43, 0xd8, 0x51, 0x18, 0x9f, 0x97, 0x9e, 0x8a, 0xe7, 0xf6, 0xf5, 0xe7, 0x22, 0x7e, 0x53,
	0x9a, 0x3c, 0x2c, 0xdc, 0xe0, 0x10, 0x9a, 0xf3, 0x84, 0xc6, 0xbc, 0xac, 0xb7, 0x6b, 0xf7, 0xd0,
	0x98, 0x87, 0x4a, 0xf7, 0x9e, 0x41, 0x43, 0x22, 0xec, 0x80, 0x71, 0x2e, 0x53, 0x98, 0xa1, 0x71,
	0x2e, 0xd8, 0x85, 0x63, 0x16, 0xec, 0x42, 0x04, 0x3a, 0x5e, 0x51, 0xc6, 0x68, 0x12, 0xb3, 0x69,
	0x46, 0xaf, 0xca, 0xf0, 0x2e, 0xb4, 0x44, 0x50, 0x31, 0x36, 0x35, 0x80, 0x8a, 0x57, 0x83, 0x31,
	0xb5, 0xc1, 0x4c, 0xe1, 0xf1, 0x83, 0x3e, 0xff, 0x39, 0x99, 0x5f, 0x06, 0x74, 0xab, 0x4e, 0xb3,
	0x28, 0xfd, 0x17, 0x43, 0x4a, 0xd3, 0x4c, 0x55, 0x1c, 0x5f, 0x41, 0xab, 0x6c, 0xe7, 0x58, 0x03,
	0x63, 0xb8, 0x37, 0xee, 0x6a, 0xf7, 0x97, 0x52, 0x58, 0x15, 0xe1, 0x01, 0xc0, 0x22, 0xb9, 0xcb,
	0x96, 0xe4, 0x2c, 0x4f, 0x89, 0xb3, 0x2d, 0xdb, 0x69, 0x27, 0xde, 0x3b, 0x6d, 0x62, 0xd2, 0x9f,
	0x0a, 0x6a, 0x83, 0x15, 0x4e, 0x3f, 0xc8, 0x8c, 0x9d, 0x50, 0x40, 0x7c, 0x02, 0xcd, 0x2f, 0xe4,
	0x9a, 0xc4, 0x57, 0xca, 0x94, 0x62, 0x2f, 0x83, 0xbf, 0x96, 0xb0, 0x07, 0xf6, 0x57, 0xff, 0xb3,
	0x1f, 0x7c, 0xf7, 0x2f, 0x8f, 0x67, 0x27, 0x8b, 0xc5, 0x49, 0xe0, 0xdb, 0x5b, 0xd8, 0x86, 0xc6,
	0x7c, 0x36, 0xbe, 0x7c, 0x6d, 0x1b, 0xb8, 0x03, 0x96, 0xff, 0xe9, 0xc8, 0x36, 0x25, 0x08, 0xee,
	0x6d, 0x4b, 0x80, 0x45, 0x70, 0x6f, 0x6f, 0x0b, 0xf0, 0x2d, 0x98, 0xd8, 0x8d, 0xf1, 0x6f, 0x13,
	0x9a, 0x22, 0xf0, 0xfb, 0x53, 0x7c, 0x2b, 0x11, 0x25, 0x0c, 0x1d, 0x2d, 0x66, 0xed, 0x6b, 0x71,
	0x9f, 0xae, 0x51, 0x8a, 0x10, 0xde, 0x16, 0x9e, 0x42, 0x47, 0xdf, 0x70, 0x3c, 0xa8, 0x17, 0x3f,
	0xfc, 0x4a, 0xdc, 0xfe, 0x46, 0xbd, 0x6a, 0x79, 0x06, 0xbb, 0xb5, 0xdd, 0xc0, 0xfe, 0x9a, 0x37,
	0xa0, 0x6f, 0x9f, 0x3b, 0xd8, 0x5c, 0xa0, 0x1b, 0xd5, 0xdf, 0x43, 0xcd, 0xe8, 0x9a, 0x05, 0x72,
	0xfb, 0x1b, 0xf5, 0xb2, 0xe5, 0x8f, 0xa6, 0xfc, 0xd3, 0x1c, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0x08, 0x33, 0xd4, 0x79, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CityAQClient is the client API for CityAQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CityAQClient interface {
	Cities(ctx context.Context, in *CitiesRequest, opts ...grpc.CallOption) (*CitiesResponse, error)
	CityGeometry(ctx context.Context, in *CityGeometryRequest, opts ...grpc.CallOption) (*CityGeometryResponse, error)
	EmissionsGrid(ctx context.Context, in *EmissionsGridRequest, opts ...grpc.CallOption) (*EmissionsGridResponse, error)
	EmissionsMap(ctx context.Context, in *EmissionsMapRequest, opts ...grpc.CallOption) (*EmissionsMapResponse, error)
}

type cityAQClient struct {
	cc *grpc.ClientConn
}

func NewCityAQClient(cc *grpc.ClientConn) CityAQClient {
	return &cityAQClient{cc}
}

func (c *cityAQClient) Cities(ctx context.Context, in *CitiesRequest, opts ...grpc.CallOption) (*CitiesResponse, error) {
	out := new(CitiesResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/Cities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) CityGeometry(ctx context.Context, in *CityGeometryRequest, opts ...grpc.CallOption) (*CityGeometryResponse, error) {
	out := new(CityGeometryResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/CityGeometry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) EmissionsGrid(ctx context.Context, in *EmissionsGridRequest, opts ...grpc.CallOption) (*EmissionsGridResponse, error) {
	out := new(EmissionsGridResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/EmissionsGrid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityAQClient) EmissionsMap(ctx context.Context, in *EmissionsMapRequest, opts ...grpc.CallOption) (*EmissionsMapResponse, error) {
	out := new(EmissionsMapResponse)
	err := c.cc.Invoke(ctx, "/cityaqrpc.CityAQ/EmissionsMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityAQServer is the server API for CityAQ service.
type CityAQServer interface {
	Cities(context.Context, *CitiesRequest) (*CitiesResponse, error)
	CityGeometry(context.Context, *CityGeometryRequest) (*CityGeometryResponse, error)
	EmissionsGrid(context.Context, *EmissionsGridRequest) (*EmissionsGridResponse, error)
	EmissionsMap(context.Context, *EmissionsMapRequest) (*EmissionsMapResponse, error)
}

// UnimplementedCityAQServer can be embedded to have forward compatible implementations.
type UnimplementedCityAQServer struct {
}

func (*UnimplementedCityAQServer) Cities(ctx context.Context, req *CitiesRequest) (*CitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cities not implemented")
}
func (*UnimplementedCityAQServer) CityGeometry(ctx context.Context, req *CityGeometryRequest) (*CityGeometryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityGeometry not implemented")
}
func (*UnimplementedCityAQServer) EmissionsGrid(ctx context.Context, req *EmissionsGridRequest) (*EmissionsGridResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmissionsGrid not implemented")
}
func (*UnimplementedCityAQServer) EmissionsMap(ctx context.Context, req *EmissionsMapRequest) (*EmissionsMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmissionsMap not implemented")
}

func RegisterCityAQServer(s *grpc.Server, srv CityAQServer) {
	s.RegisterService(&_CityAQ_serviceDesc, srv)
}

func _CityAQ_Cities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).Cities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/Cities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).Cities(ctx, req.(*CitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_CityGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).CityGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/CityGeometry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).CityGeometry(ctx, req.(*CityGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_EmissionsGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmissionsGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).EmissionsGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/EmissionsGrid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).EmissionsGrid(ctx, req.(*EmissionsGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityAQ_EmissionsMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmissionsMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityAQServer).EmissionsMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cityaqrpc.CityAQ/EmissionsMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityAQServer).EmissionsMap(ctx, req.(*EmissionsMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CityAQ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cityaqrpc.CityAQ",
	HandlerType: (*CityAQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cities",
			Handler:    _CityAQ_Cities_Handler,
		},
		{
			MethodName: "CityGeometry",
			Handler:    _CityAQ_CityGeometry_Handler,
		},
		{
			MethodName: "EmissionsGrid",
			Handler:    _CityAQ_EmissionsGrid_Handler,
		},
		{
			MethodName: "EmissionsMap",
			Handler:    _CityAQ_EmissionsMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cityaq.proto",
}
